# Практическое задание из раздела 4 - Дообучить модель классификации звука

## Подготовка IDE

### Загрузим необходимые библиотеки

In [9]:
from datasets import load_dataset, Audio
from datasets import ClassLabel
from transformers import AutoFeatureExtractor, TrainingArguments, Trainer, AutoModelForAudioClassification
from huggingface_hub import notebook_login
import evaluate
import torch


import numpy as np

## Настройка среды

In [10]:

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print('{} device is available'.format(device))

seed = 42

if torch.cuda.is_available() and device.type == 'cuda':
    np.random.seed(seed)
     # Если используете CUDA, устанавливаем seed для GPU                
    torch.cuda.manual_seed_all(seed)
    # Для полной воспроизводимости также можно зафиксировать алгоритмы cuDNN
    torch.backends.cudnn.deterministic = True   
    torch.backends.cudnn.benchmark = False
else:
    # Устанавливаем seed для CPU генератора случайных чисел PyTorch
    np.random.seed(seed)
    torch.manual_seed(seed)


# Несколько оптимизаций которые могут ускорить процесс обучения
if torch.backends.cudnn.is_available():
    print(f'Using cudnn version: {torch.backends.cudnn.version()}')
    if device.type == 'cuda':
        print(f'Using GPU: {torch.cuda.get_device_name()}')
        torch.backends.cudnn.enabled = True
        torch.backends.cudnn.benchmark = True
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True

cuda device is available
Using cudnn version: 90100
Using GPU: NVIDIA GeForce RTX 4090

## Аутентификация блокнота в HuggingFace

Для того, чтобы иметь возможность сохранить модель на HuggingFace Hub аутентифицируем блокнот:

In [11]:
notebook_login() # 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

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

## Подготовка датасета

### Описание полей датасета

Типы, связанные с каждым из полей данных, приведены ниже:
- `file`: [string] - путь к соответствующему файлу с данными,
- `audio`: содержит путь к звуковому файлу примера данных, 
- `array`: декодированная форма волны конкретного конкретного примера данных,
- `sampling_rate`: частота дискретизации (семплирования) конкретного примера данных,
- `genre`: признак классификации указывающий жанр конкретного примера данных.

### Загрузка датасет

In [12]:
gtzan = load_dataset("artyomboyko/hw5")

Resolving data files:   0%|          | 0/19 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/19 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/18 [00:00<?, ?it/s]

Разделим датасет на тренировочное и тестовое подмножества. Выделим для тестового подмножества 20% от датасета:

In [13]:
gtzan = gtzan['train'] # Обьект DatasetDict не имеет метода .train_test_split. Преобразуем DatasetDict в объект Dataset
print(type(gtzan))

gtzan = gtzan.train_test_split(seed=42, shuffle=True, test_size=0.2, stratify_by_column="genre")
gtzan

<class 'datasets.arrow_dataset.Dataset'>

DatasetDict({
    train: Dataset({
        features: ['audio', 'genre'],
        num_rows: 20970
    })
    test: Dataset({
        features: ['audio', 'genre'],
        num_rows: 5243
    })
})

Посмотрим на один из примеров датасета:

In [14]:
gtzan["train"][7]

{'audio': {'path': '1PVpuJPlRpw_30000.flac',
  'array': array([0.21835029, 0.07992041, 0.07247424, ..., 0.09402025, 0.04590464,
         0.0805732 ]),
  'sampling_rate': 16000},
 'genre': 19}

Частота дескритизации примеров датасета 22050 Гц.

### Предварительная обработка данных

Аудио- и речевые модели требуют, чтобы входные данные были закодированы в формате, который модель может обрабатывать.  Преобразование звука во входной формат осуществляется с помощью feature extractor модели. Подобно токенизаторам, 🤗 Transformers предоставляет удобный класс AutoFeatureExtractor, который может автоматически выбирать нужный экстрактор признаков для заданной модели. Начнем с инстанцирования экстрактора признаков для DistilHuBERT из предварительно обученной контрольной точки:

In [15]:
# model_id = "ntu-spml/distilhubert"
model_id = "artyomboyko/distilhubert-hw-5"
feature_extractor = AutoFeatureExtractor.from_pretrained(
    model_id, do_normalize=True, return_attention_mask=True
)

Поскольку частота дискретизации модели и набора данных различна, перед передачей аудиофайла в программу извлечения признаков его необходимо передискретизировать до 16 000 Гц. Для этого сначала нужно получить частоту дискретизации модели от экстрактора признаков:

In [16]:
sampling_rate = feature_extractor.sampling_rate
sampling_rate

16000

#### Передескретизация датасета

Используем метод cast_column для передескретизации частоты примеров датасета:

In [17]:
gtzan = gtzan.cast_column("audio", Audio(sampling_rate=sampling_rate))

Проверим частоту дескретизации примера из датасета:

In [18]:
gtzan["train"][7]

{'audio': {'path': '1PVpuJPlRpw_30000.flac',
  'array': array([0.21835029, 0.07992041, 0.07247424, ..., 0.09402025, 0.04590464,
         0.0805732 ]),
  'sampling_rate': 16000},
 'genre': 19}

#### Масштабированием признаков

Для нормальной работы модели нобходимо чтобы все значения признака находились в одном и том же динамическом диапазоне. Это позволит получить стабильность  и сходимость в процессе обучения. Перед тем, как предпринимать какие-либо действия по подготовке примеров датасета к обучению модели посмотрим какие значения средней и дисперсии имеют наши данные. Вычислим их для первого примера:

In [19]:
# Выберем первый пример из датасета
sample = gtzan["train"][0]["audio"]

# Рассчитаем среднее и дисперсию для первого примера
print(f"Mean: {np.mean(sample['array']):.3}, Variance: {np.var(sample['array']):.3}")

Mean: -3.81e-06, Variance: 0.505

Видно, что среднее значение уже близко к нулю, но дисперсия ближе к 0,05. Если бы дисперсия для выборки была больше, это могло бы вызвать проблемы с нашей моделью, так как динамический диапазон аудиоданных был бы очень мал и, следовательно, трудноразделим.
Применим экстрактор признаков и посмотрим, что получится на выходе:

In [20]:
inputs = feature_extractor(sample["array"], sampling_rate=sample["sampling_rate"])

print(f"inputs keys: {list(inputs.keys())}")

print(
    f"Mean: {np.mean(inputs['input_values']):.3}, Variance: {np.var(inputs['input_values']):.3}"
)

inputs keys: ['input_values', 'attention_mask']
Mean: 4.47e-09, Variance: 1.0

Cреднее значение теперь очень сильно приближается к нулю, а дисперсия - к единице! Именно в таком виде мы хотим получить наши аудиосэмплы перед подачей их в модель HuBERT.

Определим функцию, которую мы можем применить ко всем примерам в наборе данных. Поскольку мы ожидаем, что длина аудиоклипов будет составлять 30 секунд, мы также будем обрезать все более длинные клипы, используя аргументы max_length и truncation в экстракторе признаков следующим образом:

In [21]:
max_duration = 30.0 # Ограничение на максимальную длительность звука в секундах.


def preprocess_function(examples):
    audio_arrays = [x["array"] for x in examples["audio"]]
    inputs = feature_extractor(
        audio_arrays,
        sampling_rate=feature_extractor.sampling_rate,
        max_length=int(feature_extractor.sampling_rate * max_duration),
        truncation=True,
        return_attention_mask=True,
    )
    return inputs

Применим ее к набору данных с помощью метода map(). Метод .map() поддерживает работу с батчами сэмплов, используем эту возможность установив `batched=True`. По умолчанию размер батча составляет 1000 примеров, но мы уменьшим его до 100, чтобы пиковая нагрузка на оперативную память оставалась в разумных пределах. Кроме того, для упрощения обучения мы удалим из набора данных признаки `audio` и `file`.

Примечание: Я произвожу подготовку датасета и обучение модели на локальной машине, поэтому могу увеличить параметр определяющий количество процессов обрабатывающих примеры набора данных задав параметр `num_proc` больше 1.

In [22]:
gtzan_encoded = gtzan.map(
    preprocess_function,
    remove_columns=["audio"],
    batched=True,
    batch_size=100,
    num_proc=16,
)
gtzan_encoded

DatasetDict({
    train: Dataset({
        features: ['genre', 'input_values', 'attention_mask'],
        num_rows: 20970
    })
    test: Dataset({
        features: ['genre', 'input_values', 'attention_mask'],
        num_rows: 5243
    })
})

#### Переименование столбцов

Чтобы `Trainer` мог обрабатывать метки классов, необходимо переименовать признак `genre` в `label`:

In [23]:
gtzan_encoded = gtzan_encoded.rename_column("genre", "label")
gtzan_encoded

DatasetDict({
    train: Dataset({
        features: ['label', 'input_values', 'attention_mask'],
        num_rows: 20970
    })
    test: Dataset({
        features: ['label', 'input_values', 'attention_mask'],
        num_rows: 5243
    })
})

Теперь у нас есть подготовленный к обучению модели датасет. Перейдём к обучению модели.

#### Отображение целочисленных идентификаторов классов в строковые (человекочитаемые)

Чтобы получить от модели человекочитаемый вывод, нам необходимо реализовать функцию перехода (отображения от целочисленных идентификаторов (например, 7) к человекочитаемым меткам классов (например, "поп") и обратно. Для этого можно использовать метод int2str() следующим образом:

In [24]:
gtzan["train"].features["genre"]

ClassLabel(names=['Music', 'Water', 'Child speech, kid speaking', 'Engine', 'Female singing', 'Silence', 'Laughter', 'Outside, urban or manmade', 'Singing', 'Heavy engine (low frequency)', 'Outside, rural or natural', 'Mantra', 'Car passing by', 'Inside, large room or hall', 'Fireworks', 'Siren', 'Speech', 'Vehicle', 'Animal', 'Whack, thwack', 'Tools', 'Gunshot, gunfire', 'Sound effect', 'Whistling', 'Inside, small room', 'Vacuum cleaner', 'Snoring', 'Crowd', 'Printer', 'Bird'], id=None)

In [25]:
id2label_fn = gtzan["train"].features["genre"].int2str
id2label_fn(gtzan["train"][0]["genre"])

id2label = {
    str(i): id2label_fn(i)
    for i in range(len(gtzan_encoded["train"].features["label"].names))
}
label2id = {v: k for k, v in id2label.items()}

id2label["7"]

'Outside, urban or manmade'

## Обучение модели

### Модель классификации аудио DistilHuBert

Сначала нужно загрузить модель для данной задачи. Для этого мы можем использовать класс AutoModelForAudioClassification, который автоматически добавит соответствующую классификационную голову в нашу предварительно обученную модель DistilHuBERT. Инстанцируем модели:

In [18]:
num_labels = len(id2label)

model = AutoModelForAudioClassification.from_pretrained(
    model_id,
    # "artyomboyko/hw-5_model",
    num_labels=num_labels,
    label2id=label2id,
    id2label=id2label,
)

Следующим шагом является определение аргументов обучения, включая размер батча, количество шагов накопления градиента, количество эпох обучения и скорость обучения:

In [19]:
# model_name = model_id.split("/")[-1] # Получим название модели из её ID
# batch_size = 16 # (Нужно пробовать как у https://huggingface.co/Kurokabe/distilhubert-finetuned-gtzan-finetuned-gtzan)
# gradient_accumulation_steps = 2
# num_train_epochs = 10

# training_args = TrainingArguments(
#     f"{model_name}-finetuned-gtzan",
#     evaluation_strategy="epoch",
#     save_strategy="epoch",
#     learning_rate=5e-5,
#     adam_beta1 = 0.9,
#     adam_beta2 = 0.999,
#     adam_epsilon = 1e-08,
#     lr_scheduler_type = 'linear',
#     per_device_train_batch_size=batch_size,
#     gradient_accumulation_steps=gradient_accumulation_steps,
#     per_device_eval_batch_size=batch_size,
#     num_train_epochs=num_train_epochs,
#     warmup_ratio=0.1,
#     logging_steps=5,
#     load_best_model_at_end=True,
#     metric_for_best_model="accuracy",
#     fp16=True,
#     push_to_hub=True,
# )

model_name = model_id.split("/")[-1]
batch_size = 32
gradient_accumulation_steps = 1
num_train_epochs = 1

training_args = TrainingArguments(
    f"{model_name}-hw-5",
    eval_strategy="epoch",
    save_strategy="epoch",
    optim = "adamw_torch", #
    weight_decay=0.01, # При 0.01 дошел до F1_macro:0.34 (30 эпоха)
    learning_rate=2e-6,
    adam_beta1 = 0.9,
    adam_beta2 = 0.999,
    adam_epsilon = 1e-08,
    lr_scheduler_type = 'linear',
    per_device_train_batch_size=batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=num_train_epochs,
    warmup_ratio=0.1,
    logging_steps=5,
    load_best_model_at_end=True, #
    metric_for_best_model="balanced_accuracy", #
    greater_is_better = True, #
    report_to=["tensorboard"], #
    push_to_hub=True,
    save_total_limit=3, #
    fp16=True,              # Повышение скорости обучения
    # auto_find_batch_size=True, # Поиск оптимального размера батча
    # bf16=True,
    tf32=True,
    torch_compile=True,
    dataloader_pin_memory=True,
    dataloader_num_workers=4,
)

Определим метрику по которой мы будем оценивать качество модели. Поскольку набор данных сбалансирован, в качестве метрики мы будем использовать accuracy. Загрузим ее с помощью библиотеки 🤗 Evaluate:

In [20]:
# metric = evaluate.load("accuracy")


# def compute_metrics(eval_pred):
#     """Computes accuracy on a batch of predictions"""
#     predictions = np.argmax(eval_pred.predictions, axis=1)
#     return metric.compute(predictions=predictions, references=eval_pred.label_ids)

# metric = evaluate.load("f1")

# def compute_metrics(eval_pred):
#     """Computes F1 score on a batch of predictions"""
#     predictions = np.argmax(eval_pred.predictions, axis=1)
#     return metric.compute(predictions=predictions, references=eval_pred.label_ids, average="macro")

In [21]:
from sklearn.metrics import balanced_accuracy_score

def compute_metrics(eval_pred):
    """Computes balanced accuracy score on a batch of predictions"""
    predictions = np.argmax(eval_pred.predictions, axis=1)
    balanced_accuracy = balanced_accuracy_score(eval_pred.label_ids, predictions)
    return {"balanced_accuracy": balanced_accuracy}

Теперь у нас есть все необходимые компоненты! Давайте инстанцируем Trainer и обучим модель:

In [22]:
trainer = Trainer(
    model,
    training_args,
    train_dataset=gtzan_encoded["train"],
    eval_dataset=gtzan_encoded["test"],
    tokenizer=feature_extractor,
    compute_metrics=compute_metrics
)

/tmp/ipykernel_1503/2346129270.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [23]:
trainer.train()

TrainOutput(global_step=656, training_loss=2.072333841970781, metrics={'train_runtime': 656.8915, 'train_samples_per_second': 31.923, 'train_steps_per_second': 0.999, 'total_flos': 4.7704421680570176e+17, 'train_loss': 2.072333841970781, 'epoch': 1.0})

In [24]:
print(f"Лучшая метрика: {trainer.state.best_metric}")
print(f"Контрольная точка лучшей модели: {trainer.state.best_model_checkpoint}")

Лучшая метрика: 0.3906895633799758
Контрольная точка лучшей модели: distilhubert-hw-5-hw-5/checkpoint-656

In [25]:
# trainer.push_to_hub()

Загрузим лучшую (из полученных в процессе обучения) модель на HuggingFace Hub:

## Подготовка файла с ответами

In [4]:
test_dataset = load_dataset("artyomboyko/hw5", split="test")
test_dataset.features

Resolving data files:   0%|          | 0/19 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/19 [00:00<?, ?it/s]

{'audio': Audio(sampling_rate=None, mono=True, decode=True, id=None),
 'genre': ClassLabel(names=['Music', 'Water', 'Child speech, kid speaking', 'Engine', 'Female singing', 'Silence', 'Laughter', 'Outside, urban or manmade', 'Singing', 'Heavy engine (low frequency)', 'Outside, rural or natural', 'Mantra', 'Car passing by', 'Inside, large room or hall', 'Fireworks', 'Siren', 'Speech', 'Vehicle', 'Animal', 'Whack, thwack', 'Tools', 'Gunshot, gunfire', 'Sound effect', 'Whistling', 'Inside, small room', 'Vacuum cleaner', 'Snoring', 'Crowd', 'Printer', 'Bird'], id=None)}

In [ ]:
from tqdm import tqdm
import pandas as pd

model = AutoModelForAudioClassification.from_pretrained("artyomboyko/distilhubert-hw-5").to(device)
feature_extractor = AutoFeatureExtractor.from_pretrained("artyomboyko/distilhubert-hw-5")

results = []

# Перебираем test dataset
for sample in tqdm(test_dataset):
    # Извлекаем audio array и path
    audio_array = sample["audio"]["array"]
    path = sample["audio"]["path"]
    
    # Подготавливаем audio
    inputs = feature_extractor(audio_array, sampling_rate=feature_extractor.sampling_rate, return_tensors="pt", padding=True)
    inputs = {key: value.to(device) for key, value in inputs.items()}
    
    # Получаем предсказание
    with torch.no_grad():
        logits = model(**inputs).logits
    predicted_label_id = torch.argmax(logits, dim=-1).item()
    
    # Записываем результат
    results.append({"YTID": path, "label": id2label[str(predicted_label_id)]})

# Подготавливаем результаты и сохраняем их в файл
result_df = pd.DataFrame(results)
result_df['YTID'] = result_df['YTID'].str.replace('.flac', '', regex=False)
result_df.to_csv('result.tsv', sep='\t', index=False)

100%|██████████| 3000/3000 [00:53<00:00, 56.57it/s]

                         YTID                         label
0      _oDTEjyE75U_40000.flac                Vacuum cleaner
1     5A-8VUzAC1M_180000.flac                         Music
2      2sfvzpI4MPE_50000.flac                       Vehicle
3      M6w5HD8YIsY_60000.flac                     Whistling
4      4IEpPBzMCN4_10000.flac                        Engine
...                       ...                           ...
2995   Wj87qPZQKKw_30000.flac  Heavy engine (low frequency)
2996   37xr3DyPbwc_10000.flac                       Snoring
2997       m66t_j137lw_0.flac                        Speech
2998   9roCUZR-xzM_30000.flac                        Speech
2999   3R1FIrnVo14_30000.flac                Vacuum cleaner

[3000 rows x 2 columns]