Если вы открываете этот блокнот в colab, вам, вероятно, потребуется установить 🤗 Transformers и 🤗 Datasets. Разкомментируйте следующую ячейку и запустите ее.

In [ ]:
#! pip install datasets transformers[sentencepiece] sacrebleu

Если вы открываете этот блокнот локально, убедитесь, что в вашем окружении установлена последняя версия этих библиотек.

Чтобы иметь возможность поделиться своей моделью с сообществом и генерировать результаты, подобные тем, что показаны на рисунке ниже, через inference API, необходимо выполнить еще несколько шагов.

Сначала вам нужно сохранить свой токен аутентификации с сайта Hugging Face (зарегистрируйтесь [здесь](https://huggingface.co/join), если вы еще этого не сделали!), затем выполнить следующую ячейку и введите свое имя пользователя и пароль:

In [1]:
from huggingface_hub import notebook_login

notebook_login() # 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

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

Затем вам нужно установить Git-LFS. Раскоментируйте следующие инструкции:

In [ ]:
# !apt install git-lfs

Убедитесь, что ваша версия Transformers не ниже 4.11.0, поскольку данный функционал появился именно в этой версии:

In [32]:
import transformers

print(transformers.__version__)

4.46.1

Вы можете найти версию скрипта этого блокнота для дообучения модели в распределенном режиме с использованием нескольких GPU или TPU [здесь](https://github.com/huggingface/transformers/tree/master/examples/seq2seq ).

Мы также быстро загружаем некоторые телеметрические данные - они сообщают нам, какие примеры и версии программного обеспечения используются, чтобы мы знали, куда направить наши усилия по поддержке. Мы не собираем (и не интересуемся) никакой личной информацией, но если вы предпочитаете, чтобы вас не учитывали, можете пропустить этот шаг или полностью удалить эту ячейку.

In [33]:
from transformers.utils import send_example_telemetry

send_example_telemetry("translation_notebook", framework="pytorch")

# Дообучение модели для задачи перевода

В этом блокноте мы рассмотрим процесс дообучения одной из моделей [🤗Transformers](https://github.com/huggingface/transformers) для задачи перевода. Мы будем использовать [WMT dataset](http://www.statmt.org/wmt16/), датасет машинного перевода, составленный из коллекции различных источников, включая комментарии к новостям и парламентские заседания.

![Widget inference on a translation task](https://github.com/huggingface/notebooks/blob/main/examples/images/translation.png?raw=1)

Мы посмотрим, как легко загрузить датасет для этой задачи с помощью 🤗 Datasets и как провести дообучение модели на нем с помощью API `Trainer`.

In [34]:
# model_checkpoint = "Helsinki-NLP/opus-mt-en-ro"
model_checkpoint = "google-t5/t5-small"

Этот блокнот создан для работы с любой контрольной точкой модели из [Model Hub](https://huggingface.co/models), если у этой модели есть версия sequence-to-sequence в библиотеке Transformers. Здесь мы выбрали контрольную точку [`Helsinki-NLP/opus-mt-en-ro`](https://huggingface.co/Helsinki-NLP/opus-mt-en-ro).

## Загрузка датасета

Мы будем использовать библиотеку [🤗Datasets](https://github.com/huggingface/datasets) для загрузки данных и получения метрики, которую нам нужно использовать для оценки (для сравнения нашей модели с эталоном). Это можно легко сделать с помощью функций `load_dataset` и `load_metric`. Здесь мы используем англо-румынскую часть датасета WMT.

In [35]:
from datasets import load_dataset
from evaluate import load
raw_datasets = load_dataset("wmt16", "ro-en")
metric = load("sacrebleu")

Сам объект `dataset` представляет собой [`DatasetDict`](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasetdict), который содержит по одному ключу для обучающего, проверочного и тестового наборов:

In [36]:
raw_datasets

DatasetDict({
    train: Dataset({
        features: ['translation'],
        num_rows: 610320
    })
    validation: Dataset({
        features: ['translation'],
        num_rows: 1999
    })
    test: Dataset({
        features: ['translation'],
        num_rows: 1999
    })
})

Чтобы получить доступ к конкретному элементу, нужно сначала выбрать раздел, а затем указать индекс:

In [37]:
raw_datasets["train"][0]

{'translation': {'en': 'Membership of Parliament: see Minutes',
  'ro': 'Componenţa Parlamentului: a se vedea procesul-verbal'}}

Чтобы получить представление о том, на что похожи данные, используйте следующую функцию, которая покажет несколько примеров из датасета, выбранных случайным образом.

In [38]:
import datasets
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=5):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    for column, typ in dataset.features.items():
        if isinstance(typ, datasets.ClassLabel):
            df[column] = df[column].transform(lambda i: typ.names[i])
    display(HTML(df.to_html()))

In [39]:
show_random_elements(raw_datasets["train"])

Метрика является экземпляром [`evaluate.Metric`](https://huggingface.co/evaluate-metric):

In [40]:
metric

EvaluationModule(name: "sacrebleu", module_type: "metric", features: [{'predictions': Value(dtype='string', id='sequence'), 'references': Sequence(feature=Value(dtype='string', id='sequence'), length=-1, id='references')}, {'predictions': Value(dtype='string', id='sequence'), 'references': Value(dtype='string', id='sequence')}], usage: """
Produces BLEU scores along with its sufficient statistics
from a source against one or more references.

Args:
    predictions (`list` of `str`): list of translations to score. Each translation should be tokenized into a list of tokens.
    references (`list` of `list` of `str`): A list of lists of references. The contents of the first sub-list are the references for the first prediction, the contents of the second sub-list are for the second prediction, etc. Note that there must be the same number of references for each prediction (i.e. all sub-lists must be of the same length).
    smooth_method (`str`): The smoothing method to use, defaults to `'exp'`. Possible values are:
        - `'none'`: no smoothing
        - `'floor'`: increment zero counts
        - `'add-k'`: increment num/denom by k for n>1
        - `'exp'`: exponential decay
    smooth_value (`float`): The smoothing value. Only valid when `smooth_method='floor'` (in which case `smooth_value` defaults to `0.1`) or `smooth_method='add-k'` (in which case `smooth_value` defaults to `1`).
    tokenize (`str`): Tokenization method to use for BLEU. If not provided, defaults to `'zh'` for Chinese, `'ja-mecab'` for Japanese and `'13a'` (mteval) otherwise. Possible values are:
        - `'none'`: No tokenization.
        - `'zh'`: Chinese tokenization.
        - `'13a'`: mimics the `mteval-v13a` script from Moses.
        - `'intl'`: International tokenization, mimics the `mteval-v14` script from Moses
        - `'char'`: Language-agnostic character-level tokenization.
        - `'ja-mecab'`: Japanese tokenization. Uses the [MeCab tokenizer](https://pypi.org/project/mecab-python3).
    lowercase (`bool`): If `True`, lowercases the input, enabling case-insensitivity. Defaults to `False`.
    force (`bool`): If `True`, insists that your tokenized input is actually detokenized. Defaults to `False`.
    use_effective_order (`bool`): If `True`, stops including n-gram orders for which precision is 0. This should be `True`, if sentence-level BLEU will be computed. Defaults to `False`.

Returns:
    'score': BLEU score,
    'counts': Counts,
    'totals': Totals,
    'precisions': Precisions,
    'bp': Brevity penalty,
    'sys_len': predictions length,
    'ref_len': reference length,

Examples:

    Example 1:
        >>> predictions = ["hello there general kenobi", "foo bar foobar"]
        >>> references = [["hello there general kenobi", "hello there !"], ["foo bar foobar", "foo bar foobar"]]
        >>> sacrebleu = evaluate.load("sacrebleu")
        >>> results = sacrebleu.compute(predictions=predictions, references=references)
        >>> print(list(results.keys()))
        ['score', 'counts', 'totals', 'precisions', 'bp', 'sys_len', 'ref_len']
        >>> print(round(results["score"], 1))
        100.0

    Example 2:
        >>> predictions = ["hello there general kenobi",
        ...                 "on our way to ankh morpork"]
        >>> references = [["hello there general kenobi", "hello there !"],
        ...                 ["goodbye ankh morpork", "ankh morpork"]]
        >>> sacrebleu = evaluate.load("sacrebleu")
        >>> results = sacrebleu.compute(predictions=predictions,
        ...                             references=references)
        >>> print(list(results.keys()))
        ['score', 'counts', 'totals', 'precisions', 'bp', 'sys_len', 'ref_len']
        >>> print(round(results["score"], 1))
        39.8
""", stored examples: 0)

Вы можете вызвать его метод `compute` с вашими предсказаниями и метками, которые должны быть списком декодированных строк (список списков для меток):

In [41]:
fake_preds = ["hello there", "general kenobi"]
fake_labels = [["hello there"], ["general kenobi"]]
metric.compute(predictions=fake_preds, references=fake_labels)

{'score': 0.0,
 'counts': [4, 2, 0, 0],
 'totals': [4, 2, 0, 0],
 'precisions': [100.0, 100.0, 0.0, 0.0],
 'bp': 1.0,
 'sys_len': 4,
 'ref_len': 4}

## Предварительная обработка данных

Прежде чем мы сможем передать эти тексты в нашу модель, их необходимо предварительно обработать. Для этого используется 🤗 Transformers `Tokenizer`, который (как видно из названия) выполняет токенизацию входных данных (включая преобразование токенов в соответствующие им идентификаторы в предварительно обученном словаре) и помещает их в формат, ожидаемый моделью, а также генерирует другие входные данные, необходимые модели.

Чтобы сделать все это, мы инстанцируем наш токенизатор с помощью метода `AutoTokenizer.from_pretrained`, который обеспечит:

- мы получаем токенизатор, соответствующий архитектуре модели, которую мы хотим использовать,
- мы загружаем словарь, использованный при предварительном обучении этой конкретной контрольной точки.

Эта словарь будет кэширован, так что при следующем запуске ячейки он не будет скачиваться снова.

In [42]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

Для токенизатора mBART (как у нас здесь) необходимо задать исходный и целевой языки (чтобы тексты были правильно обработаны). Вы можете проверить коды языков [здесь](https://huggingface.co/facebook/mbart-large-cc25), если вы используете этот блокнот на разных парах языков.

In [43]:
if "mbart" in model_checkpoint:
    tokenizer.src_lang = "en-XX"
    tokenizer.tgt_lang = "ro-RO"
else:
    print("not mbart")

not mbart

По умолчанию в приведенном выше вызове будет использоваться один из быстрых токенизаторов (с поддержкой Rust) из библиотеки 🤗 Tokenizers.

Вы можете напрямую вызвать этот токенизатор для одного предложения или пары предложений:

In [44]:
tokenizer("Hello, this one sentence!")

{'input_ids': [8774, 6, 48, 80, 7142, 55, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

В зависимости от выбранной модели, вы увидите разные ключи в словаре, возвращаемые ячейкой выше. Они не имеют большого значения для того, что мы здесь делаем (просто знайте, что они требуются для модели, которую мы создадим позже), но вы можете узнать о них больше в [этом учебнике](https://huggingface.co/transformers/preprocessing.html), если вам интересно.

Вместо одного предложения мы можем передавать список предложений:

In [45]:
tokenizer(["Hello, this one sentence!", "This is another sentence."])

{'input_ids': [[8774, 6, 48, 80, 7142, 55, 1], [100, 19, 430, 7142, 5, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

Чтобы подготовить целевые объекты для нашей модели, нам нужно токенизировать их внутри контекстного менеджера `as_target_tokenizer`. Это позволит убедиться, что токенизатор использует специальные токены, соответствующие целям:

In [46]:
with tokenizer.as_target_tokenizer():
    print(tokenizer(["Hello, this one sentence!", "This is another sentence."]))

{'input_ids': [[8774, 6, 48, 80, 7142, 55, 1], [100, 19, 430, 7142, 5, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4114: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

Если вы используете одну из пяти контрольных точек T5, которые требуют специального префикса перед входом, вам следует адаптировать следующую ячейку.

In [58]:
print(model_checkpoint)

if model_checkpoint in ["google-t5/t5-small", "google-t5/t5-base", "google-t5/t5-larg", "google-t5/t5-3b", "google-t5/t5-11b"]:
    print("This is a T5 model")
    prefix = "translate English to Romanian: "
else:
    print("This is not a T5 model")
    prefix = ""

google-t5/t5-small
This is a T5 model

Затем мы можем написать функцию, которая будет предварительно обрабатывать наши примеры. Мы просто подаем их в `tokenizer` с аргументом `truncation=True`. Это гарантирует, что входные данные, длина которых превышает ту, которую может обработать выбранная модель, будут усечены до максимальной длины, принимаемой моделью. Дополнение будет обработано позже (в коллаторе данных), поэтому мы выравниваем примеры до самой большой длины в батче, а не во всем датасете.

In [ ]:
# Моё дополнение кода. Модель T5 использует большее окно контекста:
max_length = tokenizer.model_max_length
max_input_length = max_length
max_target_length = max_length

# Оригинальный код блокнота
# max_input_length = 128
# max_target_length = 128

source_lang = "en"
target_lang = "ro"

def preprocess_function(examples):
    inputs = [prefix + ex[source_lang] for ex in examples["translation"]]
    targets = [ex[target_lang] for ex in examples["translation"]]

    model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True)

    # Setup the tokenizer for targets
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(targets, max_length=max_target_length, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

Эта функция работает с одним или несколькими примерами. В случае нескольких примеров токенизатор вернет список списков для каждого ключа:

In [90]:
preprocess_function(raw_datasets['train'][:2])

{'input_ids': [[13959, 1566, 12, 3871, 29, 10, 19428, 13, 12876, 10, 217, 13687, 7, 1], [13959, 1566, 12, 3871, 29, 10, 2276, 8843, 138, 13, 13687, 7, 13, 1767, 3823, 10, 217, 13687, 7, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], 'labels': [[4961, 106, 20437, 13636, 252, 10, 3, 9, 142, 11002, 15948, 18, 11868, 138, 1], [5085, 5840, 498, 6345, 252, 18, 11868, 138, 491, 28109, 15, 23, 17875, 15, 10, 3, 9, 142, 11002, 15948, 18, 11868, 138, 1]]}

Чтобы применить эту функцию ко всем парам предложений в нашем датасете, мы просто используем метод `map` нашего объекта `dataset`, созданного ранее. В результате функция будет применена ко всем элементам всех разделений в `dataset`, так что наши обучающие, проверочные и тестовые данные будут обработаны одной командой.

In [63]:
tokenized_datasets = raw_datasets.map(preprocess_function, batched=True)

Map:   0%|          | 0/610320 [00:00<?, ? examples/s]

Map:   0%|          | 0/1999 [00:00<?, ? examples/s]

Map:   0%|          | 0/1999 [00:00<?, ? examples/s]

Что еще лучше, результаты автоматически кэшируются библиотекой 🤗 Datasets, что позволяет не тратить время на этот шаг при следующем запуске блокнота. Библиотека 🤗 Datasets обычно достаточно умна, чтобы определить, когда функция, которую вы передаете в map, изменилась (и, следовательно, требует не использовать данные кэша). Например, она правильно определит, если вы измените задачу в первой ячейке и повторно запустите блокнот. Datasets предупреждает об использовании кэшированных файлов, поэтому вы можете передать `load_from_cache_file=False` в вызове `map`, чтобы не использовать кэшированные файлы и заставить применить препроцессинг заново.

Обратите внимание, что мы передали `batched=True`, чтобы кодировать тексты батчами. Это нужно для того, чтобы использовать все преимущества быстрого токенизатора, который мы загрузили ранее и который будет использовать многопоточность для одновременной обработки текстов в батче.

## Дообучение модели

Теперь, когда наши данные готовы, мы можем загрузить предварительно обученную модель и произвести ее дообучение. Поскольку наша задача относится к типу « sequence-to-sequence», мы используем класс `AutoModelForSeq2SeqLM`. Как и в случае с токенизатором, метод `from_pretrained` загрузит и кэширует модель для нас.

In [64]:
from transformers import AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainingArguments, Seq2SeqTrainer

model = AutoModelForSeq2SeqLM.from_pretrained(model_checkpoint)

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Обратите внимание, что мы не получаем предупреждения, как в нашем примере с классификацией. Это означает, что мы использовали все веса предварительно обученной модели, и в данном случае нет случайно инициализированной головы.

Чтобы инстанцировать `Seq2SeqTrainer`, нам нужно определить еще три вещи. Самый важный - это [`Seq2SeqTrainingArguments`](https://huggingface.co/transformers/main_classes/trainer.html#transformers.Seq2SeqTrainingArguments), который представляет собой класс, содержащий все атрибуты для настройки обучения. Ему требуется одно имя папки, которая будет использоваться для сохранения контрольных точек модели, а все остальные аргументы являются необязательными:

In [77]:
batch_size = 16
epochs = 2
model_name = model_checkpoint.split("/")[-1]
args = Seq2SeqTrainingArguments(
    f"{model_name}-finetuned-{source_lang}-to-{target_lang}",
    evaluation_strategy = "epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=epochs,
    predict_with_generate=True,
    fp16=True,
    push_to_hub=True,
)

/usr/local/lib/python3.12/dist-packages/transformers/training_args.py:1559: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Здесь мы устанавливаем оценку в конце каждой эпохи, настраиваем скорость обучения, используем `batch_size`, определенный в верхней части ячейки, и настраиваем затухание веса. Поскольку `Seq2SeqTrainer` будет регулярно сохранять модель, а наш датасет довольно большой, мы указываем ему делать не более трех сохранений. Наконец, мы используем опцию `predict_with_generate` (чтобы правильно генерировать сводки) и активируем обучение со смешанной точностью (чтобы идти немного быстрее).

Последний аргумент для настройки всего, чтобы мы могли регулярно отправлять модель на [Hub](https://huggingface.co/models) во время обучения. Удалите его, если вы не следовали шагам по установке в верхней части блокнота. Если вы хотите сохранить модель локально под именем, отличным от имени хранилища, в которое она будет выложена, или если вы хотите выложить модель под организацией, а не под своим пространством имен, используйте аргумент `hub_model_id` для задания имени хранилища (это должно быть полное имя, включая ваше пространство имен: например, `«sgugger/marian-finetuned-en-to-ro»` или `«huggingface/marian-finetuned-en-to-ro»`).

Теперь нам нужен специальный коллатор данных, который не только дополнит входные данные до максимальной длины в батче, но и метки:

In [78]:
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

Последнее, что нужно определить для нашего `Seq2SeqTrainer`, это то, как вычислять метрики из предсказаний. Для этого нам нужно определить функцию, которая будет просто использовать `metric`, загруженную нами ранее, и сделать небольшую предварительную обработку для декодирования предсказаний в тексты:

In [79]:
import numpy as np

def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [[label.strip()] for label in labels]

    return preds, labels

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Some simple post-processing
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    result = {"bleu": result["score"]}

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result

Затем нам нужно просто передать все это вместе с нашими датасетами в `Seq2SeqTrainer`:

In [80]:
trainer = Seq2SeqTrainer(
    model,
    args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

/tmp/ipykernel_21004/2282859661.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

Теперь мы можем дообучить нашу модель, просто вызвав метод `train`:

In [81]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1375: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1375: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

TrainOutput(global_step=76290, training_loss=0.5905521028303415, metrics={'train_runtime': 4882.161, 'train_samples_per_second': 250.02, 'train_steps_per_second': 15.626, 'total_flos': 2.354280364297421e+16, 'train_loss': 0.5905521028303415, 'epoch': 2.0})

Теперь вы можете загрузить результат обучения в Hub, просто выполните эту инструкцию:

In [ ]:
trainer.push_to_hub()

Теперь вы можете поделиться этой моделью со всеми своими друзьями, родственниками, любимыми питомцами: все они смогут загрузить ее с идентификатором `"your-username/the-name-you-picked"`, например:

```python
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("sgugger/my-awesome-model")
```